[phases.setup]
nixPkgs = ["python311", "unixODBC", "freetds", "gnumake", "gcc", "g++"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r dialfa-analytics/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd dialfa-analytics && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 'app:create_app()'"
